spring:
  datasource:
    url: jdbc:mysql://localhost:3306/binder
    username: binder
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
---
spring:
  profiles: travis
  datasource:
    url: jdbc:postgresql://localhost:5432/binder
    username: binder
    password: KkN7{/uvw}?CKi).hDY8YSM0}YMC3QT
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
